blueprint:
  name: FireServiceRota Lights
  description: Turn a light at incident call
  domain: automation
  input:
    incident_sensor:
      name: Incident Sensor
      default: sensor.incidents
      description: The standard incident sensor added by FireServiceRota. Please select the correct one if you changed the entity name of the sensor.
      selector:
        entity:
          domain: sensor
    target_light:
      name: Lights
      description: The lights to swtich on.
      selector:
        target:
          entity:
            domain: light
    light_off_delay:
      name: Delay Light Off
      description: Time to leave the light on.
      default: 180
      selector:
        number:
          min: 5
          max: 3600
          unit_of_measurement: seconds
  source_url: https://raw.githubusercontent.com/cyberjunky/home-assistant-fireservicerota/master/blueprints/automation/fireservicerota/incident_lights.yaml

trigger:
  platform: state
  entity_id: !input incident_sensor

action:
  - service: light.turn_on
    target: !input target_light
  - delay: !input light_off_delay
  - service: light.turn_off
    target: !input target_light
